schema_version: "1.0"
name: "rdb-synth-simple-test"
models:
  - synthetics:
      data_source: __tmp__
      params:
        epochs: 600
        generator_dim: [1024, 1024]
        discriminator_dim: [1024, 1024]
        generator_lr: 0.0001
        discriminator_lr: .00033
        batch_size: 600
      generate:
        num_records: 75
        max_invalid: 50000
      privacy_filters:
        outliers: auto
        similarity: auto
